[package]
name = "unwrap-retry"
version = "0.2.0"
edition = "2024"
description = "Easily auto retrying your Results and Options"
license = "GPL-3.0-or-later"

[features]
default = ["track-caller"]
track-caller = []

[dependencies]
